#!/bin/bash
mkdir kafka 2> a
mkdir logs 2> a
mkdir logs/broker_0.log 2> a
mkdir logs/broker_1.log 2> a
mkdir logs/broker_2.log 2> a
mkdir logs/broker_3.log 2> a
mkdir logs/broker_4.log 2> a
mkdir logs/zookeeper.logs 2> a
wget http://mirrors.up.pt/pub/apache/kafka/2.2.0/kafka_2.12-2.2.0.tgz
tar -xvf kafka_2.12-2.2.0.tgz -C kafka
rm -r *.tgz a
